export const ADD_TASK = 'ALEPHLABS_ADD_TASK';
export const DROP_TASK = 'ALEPHLABS_DROP_TASK';
export const SWITCH_TASK = 'ALEPHLABS_SWITCH_TASK';
export const REORDER_TASK = 'ALEPHLABS_REORDER_TASK';